-- 코드를 입력하세요
WITH CTE AS (SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Milk'
UNION ALL
SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Yogurt'
GROUP BY CART_ID)

SELECT CART_ID
FROM CTE
GROUP BY CART_ID
HAVING COUNT(*) >= 2
ORDER BY CART_ID