SELECT DISTINCT CRCC.CAR_ID, CRCC.CAR_TYPE, FLOOR((DAILY_FEE - (DAILY_FEE * REPLACE(DISCOUNT_RATE, '%', '') / 100)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCD
ON CRCC.CAR_TYPE = CRCD.CAR_TYPE
WHERE CRCD.duration_type = '30일 이상'
AND CRCC.CAR_TYPE IN ('세단', 'SUV')
AND CRCC.CAR_ID NOT IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE NOT ((DATE_FORMAT(START_DATE, '%Y-%m-%d') < '2022-11-01' AND DATE_FORMAT(END_DATE, '%Y-%m-%d') < '2022-11-01') OR (DATE_FORMAT(START_DATE, '%Y-%m-%d') > '2022-11-30' AND DATE_FORMAT(END_DATE, '%Y-%m-%d') > '2022-11-30'))
)
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CRCC.CAR_TYPE, CRCC.CAR_ID DESC