-- 코드를 작성해주세요
SELECT ID, CASE WHEN PART <= 0.25 THEN 'CRITICAL' WHEN PART <= 0.5 THEN 'HIGH' WHEN PART <= 0.75 THEN 'MEDIUM' ELSE 'LOW' END AS COLONY_NAME
FROM (
SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PART
FROM ECOLI_DATA
) TMP
ORDER BY ID
