WITH PURCHASE AS (
    SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS
    FROM USER_INFO UI
    JOIN ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID
    WHERE YEAR(UI.JOINED) = '2021'
    GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
)

SELECT *, ROUND(PURCHASED_USERS / (SELECT COUNT(*) FROM USER_INFO UI WHERE YEAR(UI.JOINED) = '2021'), 1) AS PUCHASED_RATIO
FROM PURCHASE


