-- 코드를 작성해주세요
WITH RECURSIVE TMP AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ED.ID, ED.PARENT_ID, TP.GENERATION + 1 AS GENERATION
    FROM TMP TP
    JOIN ECOLI_DATA ED
    ON TP.ID = ED.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM TMP
WHERE ID NOT IN (
    SELECT TP1.ID
    FROM TMP TP1
    JOIN TMP TP2
    ON TP1.ID = TP2.PARENT_ID
)
GROUP BY GENERATION


