WITH DISCOUNT7 AS (
    SELECT CAST(REGEXP_REPLACE(DISCOUNT_RATE, '[^0-9]+', '') AS FLOAT) / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭'
), 
DISCOUNT30 AS (
    SELECT CAST(REGEXP_REPLACE(DISCOUNT_RATE, '[^0-9]+', '') AS FLOAT) / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭'
), 
DISCOUNT90 AS (
    SELECT CAST(REGEXP_REPLACE(DISCOUNT_RATE, '[^0-9]+', '') AS FLOAT) / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭'
)

SELECT 
    CRCH.HISTORY_ID, 
    ROUND(
        CASE 
            WHEN DATEDIFF(CRCH.END_DATE, CRCH.START_DATE) + 1 >= 7 
                AND DATEDIFF(CRCH.END_DATE, CRCH.START_DATE) + 1 < 30 
            THEN CRCC.DAILY_FEE * (1 - (SELECT DISCOUNT_RATE FROM DISCOUNT7)) * (DATEDIFF(CRCH.END_DATE, CRCH.START_DATE) + 1) 
            
            WHEN DATEDIFF(CRCH.END_DATE, CRCH.START_DATE) + 1 >= 30 
                AND DATEDIFF(CRCH.END_DATE, CRCH.START_DATE) + 1 < 90 
            THEN CRCC.DAILY_FEE * (1 - (SELECT DISCOUNT_RATE FROM DISCOUNT30)) * (DATEDIFF(CRCH.END_DATE, CRCH.START_DATE) + 1) 
            
            WHEN DATEDIFF(CRCH.END_DATE, CRCH.START_DATE) + 1 >= 90 
            THEN CRCC.DAILY_FEE * (1 - (SELECT DISCOUNT_RATE FROM DISCOUNT90)) * (DATEDIFF(CRCH.END_DATE, CRCH.START_DATE) + 1) 
            
            ELSE CRCC.DAILY_FEE * (DATEDIFF(CRCH.END_DATE, CRCH.START_DATE) + 1)
        END, 0
    ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR CRCC
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCH ON CRCC.CAR_ID = CRCH.CAR_ID
WHERE 
    CRCC.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, CRCH.HISTORY_ID DESC;