-- 코드를 작성해주세요
SELECT HE.EMP_NO, HE.EMP_NAME
, CASE WHEN SCORE >= 96 THEN 'S'
    WHEN SCORE >= 90 THEN 'A'
    WHEN SCORE >= 80 THEN 'B'
    ELSE 'C' END AS GRADE
, CASE WHEN SCORE >= 96 THEN SAL * 0.2
    WHEN SCORE >= 90 THEN SAL * 0.15
    WHEN SCORE >= 80 THEN SAL * 0.1
    ELSE 0 END AS BONUS
FROM HR_EMPLOYEES HE
JOIN (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE HG
    GROUP BY EMP_NO, YEAR
) GD
ON HE.EMP_NO = GD.EMP_NO
ORDER BY HE.EMP_NO


