-- 코드를 작성해주세요
SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, M.MAX - ED.SIZE_OF_COLONY AS YEAR_DEV, ED.ID
FROM ECOLI_DATA ED
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS MAX, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M
ON YEAR(ED.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV