-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, HG.EMP_NO, MAX(EMP_NAME) AS EMP_NAME, MAX(POSITION) AS POSITION, MAX(EMAIL) AS EMAIL
FROM HR_GRADE HG
JOIN HR_EMPLOYEES HE
ON HG.EMP_NO = HE.EMP_NO
GROUP BY HG.EMP_NO
ORDER BY SCORE desc
LIMIT 1