-- 코드를 작성해주세요

SELECT TEMP.FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, TEMP.FISH_TYPE
FROM FISH_INFO FI
JOIN (
    SELECT FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH, COUNT(*) AS FISH_COUNT
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
    HAVING AVG_LENGTH >= 33
) TEMP
ON FI.FISH_TYPE = TEMP.FISH_TYPE
GROUP BY FI.FISH_TYPE
ORDER BY TEMP.FISH_TYPE